create table if not exists public.market_name_ingredients_assoc
(
    id serial primary key,
    custom_name varchar(255) collate pg_catalog.default,
    reference_name varchar(255) collate pg_catalog.default
);

insert into market_name_ingredients_assoc (custom_name, reference_name) values
('lardons', 'PORC (poitrine) sans hachage France N.1'),
('boeuf hache', 'boeuf');


create table if not exists public.reference_index
(
    id serial primary key,
    reference_type varchar(255) collate pg_catalog.default,
    custom_name varchar(255) collate pg_catalog.default
);

insert into reference_index (reference_type, custom_name) values
('spices', 'poivre'),
('spices', 'sel'),
('spices', 'gingembre'),
('spices', 'curcuma'),
('spices', 'cumin'),
('spices', 'paprika'),
('spices', 'noix de muscade'),
('spices', 'muscade'),
('spices', 'curry'),
('spices', 'huile'),
('spices', 'huile d''olive'),
('spices', 'herbes de provence'),
('diverse_units', 'c.à.s.'),
('diverse_units', 'c.à.s'),
('diverse_units', 'cuiller à soupe'),
('diverse_units', 'cuillère à soupe'),
('diverse_units', 'cuiller a soupe'),
('diverse_units', 'cuillere a soupe'),
('diverse_units', 'c. à s.'),
('diverse_units', 'c. à soupe'),
('diverse_units', 'ca soupe'),
('diverse_units', 'soupe '),
('diverse_units', 'cas de '),
('diverse_units', 'cas d'''),
('diverse_units', 'c.à.c'),
('diverse_units', 'c.à.c.'),
('diverse_units', 'cuiller à café'),
('diverse_units', 'cuillère à café'),
('diverse_units', 'cuiller a cafe'),
('diverse_units', 'cuillere a cafe'),
('diverse_units', 'c. à café'),
('diverse_units', 'c. à c.'),
('diverse_units', 'ca cafe'),
('diverse_units', 'cac de '),
('diverse_units', 'cuiller à café'),
('diverse_units', 'cac d'''),
('diverse_units', 'verre'),
('diverse_units', 'verres'),
('diverse_units', 'kilo'),
('diverse_units', 'kilogramme'),
('diverse_units', 'kg'),
('gram_unit', 'g'),
('gram_unit', 'gramme'),
('diverse_units', 'cuiller'),
('diverse_units', 'cuillère'),
('diverse_units', 'cuillere'),
('diverse_units', 'cuilleres'),
('diverse_units', 'cuillères'),
('diverse_units', 'cuillers'),
('diverse_units', 'mg'),
('diverse_units', 'mG'),
('diverse_units', 'MG'),
('diverse_units', 'cg'),
('diverse_units', 'cG'),
('diverse_units', 'CG'),
('diverse_units', 'kg'),
('diverse_units', 'kG'),
('diverse_units', 'KG'),
('diverse_units', 'kgs'),
('diverse_units', 'kilo'),
('diverse_units', 'kilos'),
('diverse_units', 'kilogramme'),
('diverse_units', 'kilogrammes'),
('diverse_units', 'cuiller'),
('diverse_units', 'cl'),
('diverse_units', 'cL'),
('diverse_units', 'ml'),
('diverse_units', 'mL'),
('diverse_units', 'dl'),
('diverse_units', 'dL'),
('diverse_units', 'L'),
('diverse_units', ' l '),
('diverse_units', 'ML'),
('diverse_units', 'CL'),
('diverse_units', 'DL'),
('diverse_units', 'litre'),
('diverse_units', 'litres'),
('diverse_units', ' cl '),
('diverse_units', 'c.à.s.'),
('diverse_units', 'c.à.s'),
('diverse_units', 'cuiller à soupe'),
('diverse_units', 'cuillère à soupe'),
('diverse_units', 'cuiller a soupe'),
('diverse_units', 'cuillere a soupe'),
('diverse_units', 'c. à s.'),
('diverse_units', 'c. à soupe'),
('diverse_units', 'ca soupe'),
('diverse_units', 'soupe '),
('diverse_units', 'cas de '),
('diverse_units', 'cas d'''),
('diverse_units', 'c.à.c'),
('diverse_units', 'c.à.c.'),
('diverse_units', 'cuiller à café'),
('diverse_units', 'cuillère à café'),
('diverse_units', 'cuiller a cafe'),
('diverse_units', 'cuillere a cafe'),
('diverse_units', 'c. à café'),
('diverse_units', 'c. à c.'),
('diverse_units', 'ca cafe'),
('diverse_units', 'cac de '),
('diverse_units', 'cuiller à café'),
('diverse_units', 'cac d'''),
('diverse_units', 'verre'),
('diverse_units', 'verres'),
('diverse_units', 'kilo'),
('diverse_units', 'kilogramme'),
('diverse_units', 'kg'),
('diverse_units', 'pincée'),
('diverse_units', 'pincee'),
('diverse_units', 'tête'),
('diverse_units', 'tete'),
('diverse_units', 'gousse'),
('diverse_units', 'poignée'),
('diverse_units', 'poignee'),
('diverse_units', 'brin'),
('diverse_units', 'morceau');
